/** How long each demo word stays on screen before switching (milliseconds). */
export const WORD_ROTATE_MS = 4000;

export const WORDS = [
  "Welcome",
  "Bienvenue",
  "Willkommen",
  "Bienvenido",
  "Benvenuto",
  "Bem-vindo",
  "Welkom",
  "Välkommen",
  "Velkommen",
  "Tervetuloa",
  "Velkomin",
  "Vítejte",
  "Witamy",
  "Üdvözöljük",
  "Dobrodošli",
  "Добро пожаловать",
  "Ласкаво просимо",
  "Добредојде",
  "Bine ați venit",
  "Hoş geldiniz",
  "Καλώς ήρθατε",
  "مرحبا",
  "أهلا",
  "خوش آمدید",
  "स्वागत",
  "स्वागतम्",
  "স্বাগতম",
  "സ്വാഗതം",
  "வரவேற்கிறோம்",
  "స్వాగతం",
  "ಸ್ವಾಗತ",
  "સ્વાગત",
  "පිළිගනිමු",
  "ยินดีต้อนรับ",
  "សូមស្វាគមន៍",
  "Chào mừng",
  "欢迎",
  "歡迎",
  "ようこそ",
  "환영합니다",
  "Selamat datang",
  "Maligayang pagdating",
  "Mabuhay",
  "Bula",
  "Talofa",
  "Kia ora",
  "Haere mai",
  "Aloha",
  "Karibu",
  "Marhaban",
  "Barka da zuwa",
  "Byenvini",
  "Byenveni",
  "Sugeng rawuh",
  "Wilujeng sumping",
  "Manao ahoana",
  "Tongasoa",
  "Kaze neza",
  "Murakaza neza",
  "Ongi etorri",
  "Benvida",
  "Benvingut",
  "Fàilte",
  "Croeso",
  "Benvengut",
  "Bainvegni",
  "Bienvènu",
  "Bonveni",
  "Benvignû",
  "Benvegnû",
  "Bienvegni",
  "Bainvegnî",
] as const;

export function pickWord(exclude: string | null): string {
  if (WORDS.length === 0) return "";
  if (WORDS.length === 1) return WORDS[0];
  let w: string;
  do {
    w = WORDS[Math.floor(Math.random() * WORDS.length)]!;
  } while (w === exclude);
  return w;
}
